### ISSUE TITLE
Timestamp vs Time

### ISSUE THREAD

**Issue by Nheahra** [boomdevs/boomerangapp#9]
https://github.com/boomdevs/boomerangapp/blob/234cb55820c1afe80d7b4fe0fe6e85a1355fbeff/sql/boomerang-app-ddl.sql#L22

Please change timestamp to time @gessig. Thanks!

**Comment by gessig** [comment]
I just submitted a pull request.

George

**Comment by TruFyre** [comment]
Merged pull request.

**Comment by TruFyre** [comment]
@Nheahra I think this issue is handled appropriately.  Why don't you close it?
